/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'Grassy Hills',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: 60,
      targetScore: 100,
      obstacleCount: 5,
      obstacleSpeed: 1,
      collectibleCount: 10,
      collectibleValue: 10,
      backgroundTheme: 'grassy_hills',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Bouncy Platforms',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: 45,
      targetScore: 150,
      obstacleCount: 3,
      obstacleSpeed: 2,
      collectibleCount: 8,
      collectibleValue: 20,
      backgroundTheme: 'floating_islands',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Spiky Cavern',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.4,
      timeLimitSeconds: 60,
      targetScore: 200,
      obstacleCount: 10,
      obstacleSpeed: 1,
      collectibleCount: 5,
      collectibleValue: 50,
      backgroundTheme: 'dark_cavern',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Rotating Platforms',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: 90,
      targetScore: 300,
      obstacleCount: 4,
      obstacleSpeed: 3,
      collectibleCount: 3,
      collectibleValue: 100,
      backgroundTheme: 'industrial_factory',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Treacherous Traps',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: 120,
      targetScore: 450,
      obstacleCount: 15,
      obstacleSpeed: 2,
      collectibleCount: 2,
      collectibleValue: 150,
      backgroundTheme: 'ancient_ruins',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Skyward Ascent',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: 180,
      targetScore: 600,
      obstacleCount: 6,
      obstacleSpeed: 4,
      collectibleCount: 4,
      collectibleValue: 200,
      backgroundTheme: 'floating_islands',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'Neon Gauntlet',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 120,
      targetScore: 800,
      obstacleCount: 10,
      obstacleSpeed: 3,
      collectibleCount: 8,
      collectibleValue: 100,
      backgroundTheme: 'neon_city',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Crumbling Ruins',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 150,
      targetScore: 900,
      obstacleCount: 8,
      obstacleSpeed: 2,
      collectibleCount: 3,
      collectibleValue: 300,
      backgroundTheme: 'ancient_ruins',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Cyberpunk Chaos',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 180,
      targetScore: 1200,
      obstacleCount: 12,
      obstacleSpeed: 4,
      collectibleCount: 2,
      collectibleValue: 400,
      backgroundTheme: 'neon_city',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Inferno Gauntlet',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 240,
      targetScore: 1500,
      obstacleCount: 8,
      obstacleSpeed: 5,
      collectibleCount: 4,
      collectibleValue: 500,
      backgroundTheme: 'volcanic_island',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
